### ISSUE TITLE
12 contributors?

### ISSUE THREAD

**Issue by Merijn-DH** [CodingTrain/12oclocks#13]
Should we do 1 clock per person so in the end we have 12 contributors?

**Comment by TheEyeOfBrows** [comment]
I don't think we should have that restriction.

Mostly because I'd like to leave the clocks open for improvement after their first implementation (by other, new contributors), and partially because I already implemented two of them before the question was asked (oops!).

**Comment by shiffman** [comment]
Agreed! Everyone should feel free to improve and modify the clocks after they are implemented too!

**Comment by Merijn-DH** [comment]
Yeah when I posted this I was thinking about making a second clock, but I thought I would let others have a go as well. I guess that all doesn't really matter since it's a community project and anyone should be able to contribute to all clocks if they can improve it.
