### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by arjhun** [CodingTrain/12oclocks#23]
Hello,

I noticed that the 12 clocks playing simultaneously are very resource intensive. This really takes away from enjoying the clocks. The function animate() takes 50ms (chrome perfmon) and because of that the frame rate drops dramatically. I haven't checked if anything could be optimized. Maybe it's an idea to let a mouseover trigger the drawing of a clock? As seen on the following page (that i think inspired the page?). http://cmuems.com/2016/60212/lectures/lecture-09-09b-clocks/maedas-clocks/ ?

I could look into that if needed.

Cheers, 

Arjen

**Comment by meiamsome** [comment]
Absolutely. There was some discussion in #10.
If the problem is only when all clocks are simultaneously updated then it should simply be enough to step these clocks by a frame or so to even out the lag to other clocks.

But we certainly could do mouse over, too. It might requires a slight redesign of some of the clocks' internal code to reset things properly

**Comment by shiffman** [comment]
I do love seeing them all running at the same time so maybe that could live as an option (whether it's like that by default or not)

**Comment by arjhun** [comment]
@meiamsome I just implemented it and the only clock that has problems is clock 4...

@shiffman I already thought you might say that... haha don't know why. Maybe because when i'm now hovering over the clocks i'm like meh... you don't go for 'meh'!!! So I did what you said, when you hover over a clock it stops all the other. When your not on a clock they all play! 

Let me do a pull request with the things I altered see if you like it.

**Comment by sannek** [comment]
@arjhun Maybe clock 4 has problems because I specified a frame rate in its setup (none of the other ones seem to have that). When I have a chance later today, I'll look at a different way to only make it redraw/update every second (or someone else is obviously welcome to have a look at that).

**Comment by meiamsome** [comment]
@sannek The `frameRate` call you make was bypassed by me trying to fix some performance issues before. I think the main thing is just to not trust that your frames have 1 second between them, and probably to iterate through seconds from the last time up until now and add them to the array.

**Comment by sannek** [comment]
I've made a [change](https://github.com/sannek/12oclocks/blob/clock4-fix/clocks/clock-04.js) - but would like someone to have a look if it makes sense before I create a pull request.
Now, I'm keeping track of the last second, and only redrawing/updating everything if the current second is different from the previous one. I think that should make it redraw everything only once per second, regardless of frame rate. It seems to do what I want, but I might be thinking in the wrong  direction. Any suggestions?

**Comment by arjhun** [comment]
I was not saying your code has problems... The way I implemented the clocks
pausing caused clock 4 to skip frames and that sort of brakes the design.
Maybe because the whole frame needs to be updated?

Op 30 sep. 2017 1:51 p.m. schreef "Sanne" <notifications@github.com>:

**Comment by sannek** [comment]
@arjhun Ah, that makes sense. I misunderstood what you meant. It needs to catch up on the seconds it missed when paused, so it looks like it had never stopped?
I guess it could see how many seconds have passed since it was drawn, and then add all the missed times to the array before redrawing.

**Comment by arjhun** [comment]
Yessss! Thank you, I was walking while typing couldn't find the words. Hehe

Op 30 sep. 2017 5:31 p.m. schreef "Sanne" <notifications@github.com>:
