### ISSUE TITLE
Clock 3 has some... interesting... artefacts on firefox under Ubuntu

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/12oclocks#25]
Anyone else seeing similar?
![image](https://user-images.githubusercontent.com/1187491/31038451-c10f17e8-a56e-11e7-8389-06d4f5951979.png)

**Comment by TheEyeOfBrows** [comment]
Yes, although only the streaks. (not the triangle bits)
Windows 10 w/ Chrome

![image](https://user-images.githubusercontent.com/8050633/31039596-a1d51c14-a533-11e7-89e9-b725aef65a25.png)

**Comment by Oripy** [comment]
Solved with my pull request #27

**Comment by meiamsome** [comment]
@Oripy The streaking is I think fixed but the weird triangle issues I am having remain.

**Comment by Oripy** [comment]
I can't reproduce the bug on my Mac, Safari, Chrome and Firefox works fine. Maybe it is a weird bug of p5.js or Firefox on Linux? Interesting.

**Comment by waielal** [comment]
It is 11:43 o'clock right now here and I noticed this little bug.

![clock_3_bug](https://user-images.githubusercontent.com/24419899/31053478-5a6945fa-a69e-11e7-90d7-f89917ab0098.jpg)

**Comment by Oripy** [comment]
@waielal I think I fixed this with commit 9df5078a9267211214a7620ba340707c5982ac8c

Still the weird bug on Ubuntu remains

**Comment by meiamsome** [comment]
I switched up to the FF 57 beta (Was on 55 before) and the issue appears resolved. Now I am very confused!

**Comment by waielal** [comment]
Maybe there was a bug with the HTML5 canvas on Linux and they fixed it with the update?

**Comment by meiamsome** [comment]
Closing this as a browser bug
