### ISSUE TITLE
Centralise getting the time

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/12oclocks#32]
Will fix the difference between clocks (Some say 0 instead of 12).

These time functions should probably return a number so individual clocks can pad with zeros if necessary.

**Comment by meiamsome** [comment]
Well, given #34 and #35 we should probably have some discussion...

How slow are the `hour()`, `minute()` and `second()` functions - would it be more beneficial to pre-calculate them in the outer `animate` function and just store them in global variables?

**Comment by waielal** [comment]
I'm not really sure how slow they are. I looked inside the implemetation an it seems they just return `new Date().getHours()` and so on.

**Comment by meiamsome** [comment]
Looked in the performance chrome tools, and judging by that it's about 0.4% of the time in those calls - so it's probably not worth bothering? I'd be tempted to merge #34 in that case - mostly because it was in first, but suggestions welcome.

**Comment by waielal** [comment]
Well #34 and #35 don't interfere with each other. #35 just adds a new function while #34 changes the implementation of the clocks.

**Comment by meiamsome** [comment]
That's true - but #35's new function is entirely unused unless we go and change all of the instances updated in #34! I could just merge both and then if someone updates the clocks then so be it..

**Comment by waielal** [comment]
That's also true. Do as you please. I don't mind if you dont merge my PR :blush:
