### ISSUE TITLE
Clock 5 has some weird rotation

### ISSUE THREAD

**Issue by waielal** [CodingTrain/12oclocks#39]
I have noticed that the rotation of clock 5 is sometime a little bit weird.

![clock_5](https://user-images.githubusercontent.com/24419899/31068283-9e9a2974-a757-11e7-90fb-2db088f3f160.jpg)
![clock_5_2](https://user-images.githubusercontent.com/24419899/31068287-a06fd3ac-a757-11e7-9acc-44da7df6f813.jpg)

**Comment by Merijn-DH** [comment]
What's wrong with it? If you look at the original, the minutes and the seconds turn relative to the hour's rotation. 

Reference:
![image](http://cmuems.com/2016/60212/wp-content/uploads/2016/09/maeda-01.gif)

As you can see here, the hour digit is rotated to point at a 'normal' clocks 3. The minutes and seconds however are not simply pointing at their corresponding place on a clock, they seem to be offset by the angle of the hours and an additional 180 degrees. Look at the seconds when it gets to 30, you can see it has the same rotation as the 3 from hours. For the 41 you can also do the math :)

I did not make up the rotations, I guess John Maeda did. I'm just trying to represent it as accurate as possible.

**Comment by waielal** [comment]
I don't think that the minutes and seconds are relative to the hours. 

![clock_5_](https://user-images.githubusercontent.com/24419899/31071991-7ab19aec-a766-11e7-9688-dcb29264b6b3.jpg)

For 3 o'clock it works that way but you can see that at 4 o'clock it's off.
I think the top side of the hour and the right side of the minute and second are pointing in the direction of the watch hands.

**Comment by Merijn-DH** [comment]
Right, good observation! My predictions were only based on 3 o'clock. I'll change it!
