### ISSUE TITLE
Clock #9

### ISSUE THREAD

**Issue by Merijn-DH** [CodingTrain/12oclocks#9]
I don't know if the contributors on clock number 9 realize the dots of the digits are made up of small analog clocks, as can be seen here: http://cmuems.com/2016/60212/wp-content/uploads/2016/09/maeda-10.gif.

Just wanted to point this out, since I would have made the same mistake had I not zoomed in on the picture.

**Comment by meiamsome** [comment]
Yeah, it was discussed in the PR - #3, they're working on adding it. P.S. I like that Clock #9 has issue #9

**Comment by Merijn-DH** [comment]
Okay, great! Hadn't looked at that yet..

**Comment by meiamsome** [comment]
@haideralipunjabi This appears to be rebroken?

**Comment by meiamsome** [comment]
Never mind, it's just not scaling correctly - I'll fix it
